app/core/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as core

app_name = 'core'

urlpatterns = [

    # Login
    # https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.views.LoginView
    path('login/', auth_views.LoginView.as_view(template_name='core/user/auth.html'), name='login'),

    # Logout
    # https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.views.LogoutView
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Users
    path('usuarios/', core.UsersView.as_view(), name='users-list'),
    path('usuarios/novo/', core.UserCreateView.as_view(), name='user-create'),
    path('usuarios/<uuid:pk>/editar/', core.UserEditView.as_view(), name='user-edit'),
    
    # Dashboard
    path('dashboard/', core.DashboardView.as_view(), name='dashboard'),

]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Core: auth
    path('', include('app.core.urls'), name='core'),

    # Locker
    path('', include('app.locker.urls'), name='locker')
]

app/core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import uuid

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# CreateUpdateModel
# - - - - - - - - - - - - - - - - - - -
class CreateUpdateModel(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now=True)

    class Meta:
        abstract = True


# UUIDUser
# - - - - - - - - - - - - - - - - - - -
class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    # core
    cpf = models.CharField(max_length=11, null=True, blank=True, verbose_name="CPF")
    registration = models.CharField(max_length=100, null=True, blank=True, verbose_name="matrícula")

    # picture
    picture = models.ImageField(null=False, blank=True, verbose_name='picture', upload_to='accounts/%Y/%m/%d')
    picture_thumb = ImageSpecField(source='picture', processors=[ResizeToFill(200, 200)], format='JPEG', options={'quality': 60})

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

app/core/forms.py
#coding:utf-8
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import UUIDUser

# User: create
class UUIDUserForm(forms.ModelForm):

    def save(self, commit=True):
        user = super(UUIDUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = UUIDUser
        fields = ('username', 'first_name', 'email', 'password')
        labels = {
            'username': 'Login',
            'first_name': 'Nome completo',
            'email': 'Email',
        }
        widgets={
            'password': forms.PasswordInput()
        }

app/core/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse_lazy

from . import models

# Dashboard
# https://docs.djangoproject.com/en/2.0/ref/class-based-views/base/#templateview
# - - - - - - - - - - - - - - - - - - -
class DashboardView(TemplateView):

    template_name = 'core/dashboard.html'


# Users list view
# - - - - - - - - - - - - - - - - - - -
class UsersView(ListView):

    model = models.UUIDUser
    template_name = 'core/user/list.html'


# User create
# - - - - - - - - - - - - - - - - - - -
class UserCreateView(CreateView):

    model = models.UUIDUser
    template_name = 'core/user/form.html'
    success_url = reverse_lazy('core:user-list')
    fields = ['first_name', 'last_name', 'password', 'email', 'cpf', 'registration', 'picture']


# User edit
# - - - - - - - - - - - - - - - - - - -
class UserEditView(UpdateView):

    model = models.UUIDUser
    template_name = 'core/user/update.html'
    success_url = reverse_lazy('core:user-list')
    fields = ['first_name', 'last_name', 'password', 'email', 'cpf', 'registration', 'picture']

templates/core/user/auth.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Maq-larem | Gerenciador licenças | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#">HUB<b>IFPB</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Informe seu usuário e senha</p>

    <form action="{% url 'core:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group has-feedback">
        <input name="username" type="text" class="form-control" placeholder="Usuário">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="password" type="password" class="form-control" placeholder="Senha">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <!-- /.col -->
        <div class="col-xs-4 pull-right">
          <button type="submit" class="btn btn-danger btn-block btn-flat">Entrar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/core/user/form.html
{% extends '../../core/base.html' %}

{% load widget_tweaks %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
      <h1>
        Novo
        <small>usuário</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'core:users-list' %}"><i class="fa fa-building-o"></i> Usuários</a></li>
        <li class="active">Novo usuário</li>
      </ol>
    </section>
  
    <!-- Main content -->
    <section class="content">
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Formulário</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST">
          {% csrf_token %}

          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}

          <div class="box-body">
          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">{{ field.label }}</label>
              <div class="col-sm-10">
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                  <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-danger pull-right">Salvar</button>
            <a href="{% url 'core:users-list' %}" class="btn btn-default">Cancel</a>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
    </section>
  </section>
{% endblock %}

templates/core/user/list.html
{% extends '../base.html' %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Usuários
      <small>it all starts here</small>
    </h1>
    <ol class="breadcrumb">
      <a href="{% url 'core:user-create' %}" class="btn btn-sm btn-danger pull-right">Novo usuário</a>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Usuários</h3>
      </div>
      <div class="box-body no-padding">
        <table class="table table-striped">
          <tbody>
            <tr>
              <th style="width: 5%">#</th>
              <th>Nome</th>
              <th>Email</th>
              <th>CPF</th>
              <th style="width: 5%">Status</th>
            </tr>
            {% for obj in object_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a href="{% url 'core:user-edit' obj.id %}">{{ obj.first_name }} {{ obj.last_name }}</a></td>
              <td>{{ obj.email }}</td>
              <td>{{ obj.cpf }}</td>
              <td>{% if obj.is_active %}<span class="label label-success">Ativo</span>{% else %}<span class="label label-danger">Inativo</span>{% endif %}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        Footer
      </div>
      <!-- /.box-footer-->
    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
{% endblock %}

templates/core/user/update.html
{% extends '../../core/base.html' %}

{% load widget_tweaks %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
      <h1>
        Editar
        <small>usuários</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'core:users-list' %}"><i class="fa fa-building-o"></i> Usuários</a></li>
        <li class="active">Editar usuário</li>
      </ol>
    </section>
  
    <!-- Main content -->
    <section class="content">
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Formulário</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="{% url 'core:user-edit' object.pk %}" class="form-horizontal" method="POST">
          {% csrf_token %}

          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}

          <div class="box-body">
          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">{{ field.label }}</label>
              <div class="col-sm-10">
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                  <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-danger pull-right">Salvar</button>
            <a href="{% url 'core:users-list' %}" class="btn btn-default">Cancel</a>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
    </section>
  </section>
{% endblock %}