app/locker/urls.py
from __future__ import unicode_literals

from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as locker

app_name = 'locker'

urlpatterns = [
    # Projectors
    path('projetores/', locker.ProjectorView.as_view(), name='projector-list'),
    path('projetores/novo/', locker.ProjectorCreateView.as_view(), name='projector-create'),
    path('projetores/<uuid:pk>/editar/', locker.ProjectorEditView.as_view(), name='projector-edit'),

    # Reserve
    path('reserva/novo/', locker.ReserveCreateView.as_view(), name='reserve-create'),
    path('reservas/', locker.ReserveView.as_view(), name='reserve-list'),
    path('reserva/<uuid:pk>', locker.ReserveDeleteView.as_view(), name='reserve-delete'),
    path('reserva/<uuid:pk>', locker.ReserveDetailView.as_view(), name='reserve-detail'),

]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Core: auth
    path('', include('app.core.urls'), name='core'),

    # Locker
    path('', include('app.locker.urls'), name='locker')
]

app/locker/models.py
from django.db import models
from app.core.models import CreateUpdateModel, UUIDUser

# Projector
# - - - - - - - - - - - - - - - - - - -
class Projector (CreateUpdateModel):

	Computador_Interativo = "Interativo"
	Datashow = "Datashow"
	TYPE = (
		(Datashow, "Datashow"),
		(Computador_Interativo, "Interativo")
		)

	HDMI = "HDMI"
	VGA = "VGA"
	CABLE = (
		(HDMI, "HDMI"), 
		(VGA, "VGA")
		)

	tipping = models.CharField(max_length=255, null=False, blank=False, unique=True, verbose_name='Tombamento')
	status = models.BooleanField(null=False, verbose_name='Disponibilidade')
	type = models.CharField(max_length=10, choices=TYPE, default=Datashow, verbose_name='Tipo')
	note = models.CharField(max_length=255, null=True, blank=True, verbose_name='Notas')
	cable = models.CharField(max_length=4, choices=CABLE, default=VGA, verbose_name='Tipo')

	def __str__(self):
		return "%s" % (self.tipping)

	class Meta:
		verbose_name = 'Projetor'
		verbose_name_plural = 'Projetores'
		
# Reserve
# - - - - - - - - - - - - - - - - - - -
class Reserve (CreateUpdateModel):

	user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, null=False, verbose_name='Usuário')
	date = models.DateField(auto_now=False, auto_now_add=False,verbose_name='Data')
	projector = models.ForeignKey('Projector', on_delete=models.CASCADE, null=False, verbose_name='Projetor')
	slots = models.ManyToManyField('Slot', verbose_name="Slot")

	def __str__(self):
		return self.user.first_name

	class Meta:
		verbose_name = 'Reserva'
		verbose_name_plural = 'Reservas'

# Rate
# - - - - - - - - - - - - - - - - - - -
class Rate (CreateUpdateModel):

	rate = models.TextField(null=False, verbose_name='Avaliação')
	user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, null=False, verbose_name='Usuário')
	projector = models.ForeignKey('Projector', on_delete=models.CASCADE, null=False, verbose_name='Projetor')

	def __str__(self):
		return self.first_name

	class Meta:
		verbose_name = 'Avaliação'
		verbose_name_plural = 'Avaliações'

# Slot
# - - - - - - - - - - - - - - - - - - -
class Slot (CreateUpdateModel):

	TURNS = (
		(0, "Manhã"), 
		(1, "Tarde"),
		(2, "Noite")
	)

	name = models.CharField(max_length=255, null=False, blank=False, verbose_name='Nome')
	start = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='Horário Início')
	end = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='Horário Final')
	turn = models.IntegerField(choices= TURNS)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Slot'
		verbose_name_plural = 'Slots'

app/locker/forms.py
from django import forms

from .models import Projector

# User: create
class ProjectorForm(forms.ModelForm):

    def save(self, commit=True):
        projector = super(ProjectorForm, self).save(commit=False)
        if commit:
            projector.save()
        return projector

    class Meta:

        model = Projector

app/locker/views.py
from datetime import datetime, timedelta

from django.shortcuts import render

from django.http import HttpResponseRedirect

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy, reverse

from . import models

# Projectors list view
#-------------------
class ProjectorView(ListView):

    model = models.Projector
    template_name = 'locker/projector/list.html'

# Projector create view
#-------------------
class ProjectorCreateView(CreateView):

    model = models.Projector
    template_name = 'locker/projector/form.html'
    success_url = reverse_lazy('locker:projector-list')
    fields = ['tipping', 'type', 'note', 'cable','status']

# Projector edit
#-------------------
class ProjectorEditView(UpdateView):

    model = models.Projector
    template_name = 'locker/projector/update.html'
    success_url = reverse_lazy('locker:projector-list')
    fields = ['tipping', 'type', 'note', 'cable', 'status']


#Reserve list view
#-------------------
class ReserveView(ListView):

    model = models.Reserve
    template_name = 'locker/reserve/list.html'

    def get_context_data(self, **kwargs):
        if self.request.user.is_staff:
            kwargs['object_list'] = models.Reserve.objects.all()
        else:
            kwargs['object_list'] = models.Reserve.objects.filter(user = self.request.user)
        return super(ReserveView, self).get_context_data(**kwargs) 

# Reserve create view
#-------------------
class ReserveCreateView(TemplateView):
    
    #model = models.Reserve
    template_name = 'locker/reserve/reserve.html'
    #success_url = reverse_lazy('locker:projector-list')
    #fields = ['user', 'date', 'projector', 'slots']

    def get_context_data(self, **kwargs):
        # TODO: Se a data nao vier na URL
        date = datetime.today()
        # Days
        kwargs['days'] = []
        i = 1
        for day in range(0, date.weekday()):
            kwargs['days'].append( (date - timedelta(days=i)).day )
            i += 1
        
        i = 0
        for day in range(date.weekday(), 5):
            kwargs['days'].append( (date + timedelta(days=i)).day )
            i += 1

        # Slots
        kwargs['slots'] = models.Slot.objects.all().order_by('turn', 'name')
        return super(ReserveCreateView, self).get_context_data(**kwargs)
    
    def post(self, request, *args, **kwargs):
        r = models.Reserve()
        tipo = request.POST.get("erro")
        reserves = models.Reserve.objects.all()
        projectors = models.Projector.objects.all()
        r.user = self.request.user
        r.date = datetime.now()
        # TODO: Search projector
        for p in projectors:
            if tipo == p.type:
                for res in reserves:
                    if res.projector == p:
                        pass
                    else:    
                        r.projector = models.Projector.objects.get(p.tipping)
        #r.projector = models.Projector.objects.first()
        # TODO: Ver uma forma melhor de pegar os dias
        r.save()
        #r.slots.add(self.request.POST['4'])
        #r.save()

        return HttpResponseRedirect(reverse('locker:reserve-list'))

# Reserve remove view 
#-------------------
class ReserveDeleteView(DeleteView):
    
    model = models.Reserve
    success_url = reverse_lazy('locker:reserve-list')
    
# Reserver detail view
#-------------------
class ReserveDetailView(DetailView):

    model = models.Reserve
    template_name = 'locker/reserve_confirm_delate.html'

templates/locker/reserve/detail_confirm_delete.html
{% extends '../../core/base.html' %}

{% load widget_tweaks %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
      <h1>
        Detalhes
        <small>reservas</small>
      </h1>
      <ol class="breadcrumb">
        <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
      </ol>
    </section>
  
    <!-- Main content -->
    <section class="content">
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Formulário</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="{% url 'locker:projector-edit' object.pk %}" class="form-horizontal" method="POST">
          {% csrf_token %}

          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="inputProjector" class="col-sm-2 control-label">{{ field.label }}</label>
               <div class="col-sm-10">
                 {{ field|add_class:'form-control' }}
                  {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                  {% endfor %}
                </div>
                {%endif%}
              {% endif %}
            </div>
          {% endfor %}
          <div class="box-body">
          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-sucess pull-right">Salvar</button>
            <a href="{% url 'locker:projector-list' %}" class="btn btn-default">Cancel</a>
          </div>
          </form>
          <!-- /.box-footer -->
        </form>
      </div>
    </section>
  </section>
{% endblock %}

templates/locker/reserve/list.html
{% extends '../../core/base.html' %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Reservas
    </h1>
    <ol class="breadcrumb">
      <a href="{% url 'locker:reserve-create' %}" class="btn btn-sm btn-danger pull-right">Nova reserva</a>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Reservas</h3>
      </div>
      <div class="box-body no-padding">
        <table class="table table-striped">
          <tbody>
            <tr>
              <th style="width: 5%">#</th>
              <th>Usuário</th>
              <th>Data</th>
              <th>Projetor</th>
              <th>Horário</th>
            </tr>
            {% for obj in object_list %}
              <tr>
                <td><a href="{% url 'locker:reserve-detail' obj.id %}">{{ forloop.counter }}</a></td>
                <td>{{ obj.user.first_name }}</td>
                <td>{{ obj.date }}</td>
                <td>{{ obj.projector }}</td>
                <td>
                {% for s in obj.slots.all %}
                  {{ s.name }},
                {% endfor %}
                </td>
              </tr>
            {% endfor %}
            
         </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        Footer
      </div>
      <!-- /.box-footer-->
    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
{% endblock %}

templates/locker/reserve/reserve.html
{% extends '../../core/base.html' %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Reservas
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Examples</a></li>
      <li class="active">Blank page</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Projetor</h3>
          <select name="projetor" id="erro">
            <option value="" selected="">Escolha um projetor</option>
            <option value="Interativo">Computador Interativo</option>
            <option value="Datashow">Datashow</option>
          </select>
        </div>
      <div class="box-body">
          <!-- action="{% url 'locker:reserve-list' %}"-->
          <form id="click" method="POST" onsubmit="return false;">
              {% csrf_token %}
              <table class="table table-hover table-bordered">
                <thead>
                    <tr class="success">
                        <td class="text-center">Horário</td>
                            <td class="text-center">Segunda ({{ days.0 }})</td>
                            <td class="text-center">Terça ({{ days.1 }})</td>
                            <td class="text-center">Quarta ({{ days.2 }})</td>
                            <td class="text-center">Quinta ({{ days.3 }})</td>
                            <td class="text-center">Sexta ({{ days.4 }})</td>
                    </tr>
                </thead>
                <tbody class="checkbox-group required">
                  {% for slot in slots %}
                  <tr id="marcadores">
                        <td class="text-center" style="vertical-align:middle"> {{ slot.name }}<br/>{{ slot.start }} - {{ slot.end }}</td>
                        <td class="text-center" style="vertical-align:middle"> <input type="checkbox" name="{{ days.0 }}" value= {{ slot.pk }} onclick="pop()"> </td>
                        <td class="text-center" style="vertical-align:middle"> <input type="checkbox" name="{{ days.1 }}" value= {{ slot.pk }} onclick="pop()"> </td>
                        <td class="text-center" style="vertical-align:middle"> <input type="checkbox" name="{{ days.2 }}" value= {{ slot.pk }} onclick="pop()"> </td>
                        <td class="text-center" style="vertical-align:middle"> <input type="checkbox" name="{{ days.3 }}" value= {{ slot.pk }} onclick="pop()"> </td>
                        <td class="text-center" style="vertical-align:middle"> <input type="checkbox" name="{{ days.4 }}" value= {{ slot.pk }} onclick="pop()"> </td>
                    </tr>
                  {% endfor %}  
                  </tbody>
              </table>      

              <button type="submit" class="btn btn-danger pull-right" id="Salvar" disabled >Salvar</button>
              <script> 
                function pop() {
                  const button = document.getElementById("Salvar").disabled
                  if(button){
                    document.getElementById("Salvar").disabled = false
                  }
                  else {
                    let markers = document.getElementsByTagName('input')
                    let array = []
                    let a = 0
                    for (let index = 0; index < markers.length-1; index++) {
                      if(markers[index].type == "checkbox"){
                        array[a] = markers[index]
                        a++
                      }
                    }
                    let checked = false
                    for (let index = 0; index < array.length-1; index++) {
                      if(array[index].checked==true){
                        checked = true
                        break
                      }
                    }
                    if(!checked){
                      alert("Escolha pelo menos um horário!")
                      document.getElementById("Salvar").disabled = true
                    }
                  }
            
                click.onsubmit = function success() {
                  if(erro.value == ""){
                      var vaiErro = new vaiDarErro();
                      return false;
                  } else alert("Sucesso!");
                }
                function vaiDarErro(){
                    alert("Selecione um projetor");
                }
                  
                }
              </script>
              <a href="{% url 'locker:reserve-list' %}" class="btn btn-default">Cancel</a>
            </form>    
      </div>
    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
{% endblock %}